modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
    modId="openblocksrenewed"
    version="${file.jarVersion}"
    displayName="OpenBlocks: Renewed"
    credits="LegionModding and OpenMods team for the original OpenBlocks mod!"
    authors="LegionModding"
    description='''This is an unofficial port of OpenBlocks to 1.16 and beyond with new blocks and features!'''
[[dependencies.openblocksrenewed]]
    modId="forge"
    mandatory=true
    versionRange="[36.2.23,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.openblocksrenewed]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.openblocksrenewed]]
    modId="yalm"
    mandatory=true
    versionRange="[forge-0.0.8,forge-0.1.0)"
    ordering="NONE"
    side="BOTH"